// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/HandledPicture.proto

package ru.shadowsparky.screencast.proto;

public final class HandledPictureOuterClass {
  private HandledPictureOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HandledPictureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.shadowsparky.screencast.proto.HandledPicture)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes encoded_picture = 1;</code>
     */
    com.google.protobuf.ByteString getEncodedPicture();

    /**
     * <code>optional int32 flags = 2;</code>
     */
    int getFlags();
  }
  /**
   * Protobuf type {@code ru.shadowsparky.screencast.proto.HandledPicture}
   */
  public  static final class HandledPicture extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.shadowsparky.screencast.proto.HandledPicture)
      HandledPictureOrBuilder {
    // Use HandledPicture.newBuilder() to construct.
    private HandledPicture(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HandledPicture() {
      encodedPicture_ = com.google.protobuf.ByteString.EMPTY;
      flags_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HandledPicture(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              encodedPicture_ = input.readBytes();
              break;
            }
            case 16: {

              flags_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.shadowsparky.screencast.proto.HandledPictureOuterClass.internal_static_ru_shadowsparky_screencast_proto_HandledPicture_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.shadowsparky.screencast.proto.HandledPictureOuterClass.internal_static_ru_shadowsparky_screencast_proto_HandledPicture_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture.class, ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture.Builder.class);
    }

    public static final int ENCODED_PICTURE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encodedPicture_;
    /**
     * <code>optional bytes encoded_picture = 1;</code>
     */
    public com.google.protobuf.ByteString getEncodedPicture() {
      return encodedPicture_;
    }

    public static final int FLAGS_FIELD_NUMBER = 2;
    private int flags_;
    /**
     * <code>optional int32 flags = 2;</code>
     */
    public int getFlags() {
      return flags_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!encodedPicture_.isEmpty()) {
        output.writeBytes(1, encodedPicture_);
      }
      if (flags_ != 0) {
        output.writeInt32(2, flags_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!encodedPicture_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encodedPicture_);
      }
      if (flags_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flags_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture)) {
        return super.equals(obj);
      }
      ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture other = (ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture) obj;

      boolean result = true;
      result = result && getEncodedPicture()
          .equals(other.getEncodedPicture());
      result = result && (getFlags()
          == other.getFlags());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ENCODED_PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getEncodedPicture().hashCode();
      hash = (37 * hash) + FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getFlags();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.shadowsparky.screencast.proto.HandledPicture}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.shadowsparky.screencast.proto.HandledPicture)
        ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPictureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.shadowsparky.screencast.proto.HandledPictureOuterClass.internal_static_ru_shadowsparky_screencast_proto_HandledPicture_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.shadowsparky.screencast.proto.HandledPictureOuterClass.internal_static_ru_shadowsparky_screencast_proto_HandledPicture_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture.class, ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture.Builder.class);
      }

      // Construct using ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        encodedPicture_ = com.google.protobuf.ByteString.EMPTY;

        flags_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.shadowsparky.screencast.proto.HandledPictureOuterClass.internal_static_ru_shadowsparky_screencast_proto_HandledPicture_descriptor;
      }

      public ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture getDefaultInstanceForType() {
        return ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture.getDefaultInstance();
      }

      public ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture build() {
        ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture buildPartial() {
        ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture result = new ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture(this);
        result.encodedPicture_ = encodedPicture_;
        result.flags_ = flags_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture) {
          return mergeFrom((ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture other) {
        if (other == ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture.getDefaultInstance()) return this;
        if (other.getEncodedPicture() != com.google.protobuf.ByteString.EMPTY) {
          setEncodedPicture(other.getEncodedPicture());
        }
        if (other.getFlags() != 0) {
          setFlags(other.getFlags());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString encodedPicture_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes encoded_picture = 1;</code>
       */
      public com.google.protobuf.ByteString getEncodedPicture() {
        return encodedPicture_;
      }
      /**
       * <code>optional bytes encoded_picture = 1;</code>
       */
      public Builder setEncodedPicture(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encodedPicture_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes encoded_picture = 1;</code>
       */
      public Builder clearEncodedPicture() {
        
        encodedPicture_ = getDefaultInstance().getEncodedPicture();
        onChanged();
        return this;
      }

      private int flags_ ;
      /**
       * <code>optional int32 flags = 2;</code>
       */
      public int getFlags() {
        return flags_;
      }
      /**
       * <code>optional int32 flags = 2;</code>
       */
      public Builder setFlags(int value) {
        
        flags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 flags = 2;</code>
       */
      public Builder clearFlags() {
        
        flags_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ru.shadowsparky.screencast.proto.HandledPicture)
    }

    // @@protoc_insertion_point(class_scope:ru.shadowsparky.screencast.proto.HandledPicture)
    private static final ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture();
    }

    public static ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HandledPicture>
        PARSER = new com.google.protobuf.AbstractParser<HandledPicture>() {
      public HandledPicture parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HandledPicture(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HandledPicture> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HandledPicture> getParserForType() {
      return PARSER;
    }

    public ru.shadowsparky.screencast.proto.HandledPictureOuterClass.HandledPicture getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_shadowsparky_screencast_proto_HandledPicture_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_shadowsparky_screencast_proto_HandledPicture_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/proto/HandledPicture.proto\022 r" +
      "u.shadowsparky.screencast.proto\"8\n\016Handl" +
      "edPicture\022\027\n\017encoded_picture\030\001 \001(\014\022\r\n\005fl" +
      "ags\030\002 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ru_shadowsparky_screencast_proto_HandledPicture_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_shadowsparky_screencast_proto_HandledPicture_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_shadowsparky_screencast_proto_HandledPicture_descriptor,
        new java.lang.String[] { "EncodedPicture", "Flags", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
